# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:9.5
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
